/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.DaoCategoria;
import controlador.DaoCliente;
import controlador.DaoEntrada;
import controlador.DaoProducto;
import controlador.DaoProveedor;
import controlador.DaoSalida;
import controlador.DaoUsuario;
import java.awt.Color;

/**
 *
 * @author Rafael
 */
public class Principal extends javax.swing.JPanel {
    DaoCategoria daoCats=new DaoCategoria();
    DaoCliente daoCls=new DaoCliente();
    DaoProveedor daoPrv=new DaoProveedor();
    DaoSalida daoSld=new DaoSalida();
    DaoUsuario daoUsr=new DaoUsuario();
    DaoProducto daoPrd=new DaoProducto();
    DaoEntrada daoEtd=new DaoEntrada();
    
    public Principal() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        txtCantCat.setText(daoCats.CantCtgrs()+"");
        txtCantClt.setText(daoCls.CantClnts()+"");
        txtCantidadProv.setText(daoPrv.CantProvs()+"");
        txtCantSal.setText(daoSld.CantSlds()+"");
        txtCantEtd.setText(daoEtd.CantEtds()+"");
        txtCantPrds.setText(daoPrd.CantPrds()+"");
        txtCantUsrs.setText(daoUsr.CantUsrs()+"");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelRound1 = new modelo.JpanelRound();
        jLabel1 = new javax.swing.JLabel();
        txtCantSal = new javax.swing.JLabel();
        jpanelRound2 = new modelo.JpanelRound();
        jLabel3 = new javax.swing.JLabel();
        txtCantClt = new javax.swing.JLabel();
        jpanelRound3 = new modelo.JpanelRound();
        jLabel5 = new javax.swing.JLabel();
        txtCantEtd = new javax.swing.JLabel();
        txtCantProvs = new modelo.JpanelRound();
        jLabel7 = new javax.swing.JLabel();
        txtCantidadProv = new javax.swing.JLabel();
        jpanelRound5 = new modelo.JpanelRound();
        jLabel9 = new javax.swing.JLabel();
        txtCantCat = new javax.swing.JLabel();
        txtCantUsr = new modelo.JpanelRound();
        jLabel11 = new javax.swing.JLabel();
        txtCantUsrs = new javax.swing.JLabel();
        txtCantUsr1 = new modelo.JpanelRound();
        jLabel12 = new javax.swing.JLabel();
        txtCantPrds = new javax.swing.JLabel();

        setBackground(new java.awt.Color(238, 238, 238));

        jpanelRound1.setBackground(new java.awt.Color(81, 131, 50));
        jpanelRound1.setPreferredSize(new java.awt.Dimension(200, 88));
        jpanelRound1.setRoundBottomLeft(25);
        jpanelRound1.setRoundBottomRight(25);
        jpanelRound1.setRoundTopLeft(25);
        jpanelRound1.setRoundTopRight(25);

        jLabel1.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SALIDAS");

        txtCantSal.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        txtCantSal.setForeground(new java.awt.Color(255, 255, 255));
        txtCantSal.setText("0");

        javax.swing.GroupLayout jpanelRound1Layout = new javax.swing.GroupLayout(jpanelRound1);
        jpanelRound1.setLayout(jpanelRound1Layout);
        jpanelRound1Layout.setHorizontalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound1Layout.createSequentialGroup()
                        .addComponent(txtCantSal)
                        .addGap(86, 86, 86))))
        );
        jpanelRound1Layout.setVerticalGroup(
            jpanelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantSal)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpanelRound2.setBackground(new java.awt.Color(81, 131, 50));
        jpanelRound2.setPreferredSize(new java.awt.Dimension(200, 88));
        jpanelRound2.setRoundBottomLeft(25);
        jpanelRound2.setRoundBottomRight(25);
        jpanelRound2.setRoundTopLeft(25);
        jpanelRound2.setRoundTopRight(25);

        jLabel3.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CLIENTES");

        txtCantClt.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        txtCantClt.setForeground(new java.awt.Color(255, 255, 255));
        txtCantClt.setText("0");

        javax.swing.GroupLayout jpanelRound2Layout = new javax.swing.GroupLayout(jpanelRound2);
        jpanelRound2.setLayout(jpanelRound2Layout);
        jpanelRound2Layout.setHorizontalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound2Layout.createSequentialGroup()
                        .addComponent(txtCantClt)
                        .addGap(87, 87, 87))))
        );
        jpanelRound2Layout.setVerticalGroup(
            jpanelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantClt)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpanelRound3.setBackground(new java.awt.Color(81, 131, 50));
        jpanelRound3.setForeground(new java.awt.Color(0, 0, 0));
        jpanelRound3.setPreferredSize(new java.awt.Dimension(200, 88));
        jpanelRound3.setRoundBottomLeft(25);
        jpanelRound3.setRoundBottomRight(25);
        jpanelRound3.setRoundTopLeft(25);
        jpanelRound3.setRoundTopRight(25);

        jLabel5.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ENTRADAS");

        txtCantEtd.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        txtCantEtd.setForeground(new java.awt.Color(255, 255, 255));
        txtCantEtd.setText("0");

        javax.swing.GroupLayout jpanelRound3Layout = new javax.swing.GroupLayout(jpanelRound3);
        jpanelRound3.setLayout(jpanelRound3Layout);
        jpanelRound3Layout.setHorizontalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound3Layout.createSequentialGroup()
                        .addComponent(txtCantEtd)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(47, 47, 47))))
        );
        jpanelRound3Layout.setVerticalGroup(
            jpanelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantEtd)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        txtCantProvs.setBackground(new java.awt.Color(81, 131, 50));
        txtCantProvs.setPreferredSize(new java.awt.Dimension(200, 88));
        txtCantProvs.setRoundBottomLeft(25);
        txtCantProvs.setRoundBottomRight(25);
        txtCantProvs.setRoundTopLeft(25);
        txtCantProvs.setRoundTopRight(25);

        jLabel7.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PROVEEDORES");

        txtCantidadProv.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        txtCantidadProv.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidadProv.setText("0");

        javax.swing.GroupLayout txtCantProvsLayout = new javax.swing.GroupLayout(txtCantProvs);
        txtCantProvs.setLayout(txtCantProvsLayout);
        txtCantProvsLayout.setHorizontalGroup(
            txtCantProvsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCantProvsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(33, 33, 33))
            .addGroup(txtCantProvsLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(txtCantidadProv)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        txtCantProvsLayout.setVerticalGroup(
            txtCantProvsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCantProvsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantidadProv)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jpanelRound5.setBackground(new java.awt.Color(81, 131, 50));
        jpanelRound5.setPreferredSize(new java.awt.Dimension(200, 88));
        jpanelRound5.setRoundBottomLeft(25);
        jpanelRound5.setRoundBottomRight(25);
        jpanelRound5.setRoundTopLeft(25);
        jpanelRound5.setRoundTopRight(25);

        jLabel9.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CATEGORIAS");

        txtCantCat.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        txtCantCat.setForeground(new java.awt.Color(255, 255, 255));
        txtCantCat.setText("0");

        javax.swing.GroupLayout jpanelRound5Layout = new javax.swing.GroupLayout(jpanelRound5);
        jpanelRound5.setLayout(jpanelRound5Layout);
        jpanelRound5Layout.setHorizontalGroup(
            jpanelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelRound5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtCantCat)
                .addGap(91, 91, 91))
        );
        jpanelRound5Layout.setVerticalGroup(
            jpanelRound5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelRound5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantCat)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        txtCantUsr.setBackground(new java.awt.Color(81, 131, 50));
        txtCantUsr.setPreferredSize(new java.awt.Dimension(200, 88));
        txtCantUsr.setRoundBottomLeft(25);
        txtCantUsr.setRoundBottomRight(25);
        txtCantUsr.setRoundTopLeft(25);
        txtCantUsr.setRoundTopRight(25);

        jLabel11.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("USUARIOS");

        txtCantUsrs.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        txtCantUsrs.setForeground(new java.awt.Color(255, 255, 255));
        txtCantUsrs.setText("0");

        javax.swing.GroupLayout txtCantUsrLayout = new javax.swing.GroupLayout(txtCantUsr);
        txtCantUsr.setLayout(txtCantUsrLayout);
        txtCantUsrLayout.setHorizontalGroup(
            txtCantUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCantUsrLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(49, 49, 49))
            .addGroup(txtCantUsrLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(txtCantUsrs)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        txtCantUsrLayout.setVerticalGroup(
            txtCantUsrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCantUsrLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantUsrs)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        txtCantUsr1.setBackground(new java.awt.Color(81, 131, 50));
        txtCantUsr1.setPreferredSize(new java.awt.Dimension(200, 88));
        txtCantUsr1.setRoundBottomLeft(25);
        txtCantUsr1.setRoundBottomRight(25);
        txtCantUsr1.setRoundTopLeft(25);
        txtCantUsr1.setRoundTopRight(25);

        jLabel12.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PRODUCTOS");

        txtCantPrds.setFont(new java.awt.Font("Century751 BT", 1, 18)); // NOI18N
        txtCantPrds.setForeground(new java.awt.Color(255, 255, 255));
        txtCantPrds.setText("0");

        javax.swing.GroupLayout txtCantUsr1Layout = new javax.swing.GroupLayout(txtCantUsr1);
        txtCantUsr1.setLayout(txtCantUsr1Layout);
        txtCantUsr1Layout.setHorizontalGroup(
            txtCantUsr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCantUsr1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(txtCantUsr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtCantUsr1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, txtCantUsr1Layout.createSequentialGroup()
                        .addComponent(txtCantPrds)
                        .addGap(91, 91, 91))))
        );
        txtCantUsr1Layout.setVerticalGroup(
            txtCantUsr1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtCantUsr1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCantPrds)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCantProvs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpanelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCantUsr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpanelRound2, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(jpanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jpanelRound3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCantUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpanelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanelRound5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCantProvs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpanelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addComponent(txtCantUsr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private modelo.JpanelRound jpanelRound1;
    private modelo.JpanelRound jpanelRound2;
    private modelo.JpanelRound jpanelRound3;
    private modelo.JpanelRound jpanelRound5;
    private javax.swing.JLabel txtCantCat;
    private javax.swing.JLabel txtCantClt;
    private javax.swing.JLabel txtCantEtd;
    private javax.swing.JLabel txtCantPrds;
    private modelo.JpanelRound txtCantProvs;
    private javax.swing.JLabel txtCantSal;
    private modelo.JpanelRound txtCantUsr;
    private modelo.JpanelRound txtCantUsr1;
    private javax.swing.JLabel txtCantUsrs;
    private javax.swing.JLabel txtCantidadProv;
    // End of variables declaration//GEN-END:variables
}
